"""add admin confirmation fields fixed

Revision ID: 562f5513b09a
Revises: d392c44d3137
Create Date: 2026-02-12 10:01:34.902386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '562f5513b09a'
down_revision: Union[str, Sequence[str], None] = 'd392c44d3137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - focused on consumption table."""
    # Add confirmation workflow fields to consumption table
    with op.batch_alter_table('consumption', schema=None) as batch_op:
        # These are the fields the backend is currently complaining about
        batch_op.add_column(sa.Column('requested_quantity', sa.Numeric(precision=12, scale=3), nullable=True))
        batch_op.add_column(sa.Column('requested_extra_qty', sa.Numeric(precision=12, scale=3), nullable=True))
        batch_op.add_column(sa.Column('request_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('request_note', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_by', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_consumption_confirmed_by', 'users', ['confirmed_by'], ['id'])
    
    # Try to create missing tables if they don't exist, but skip if they do
    # We'll use try-except or check existence manually since this is SQLite
    # However, for now, the priority is the consumption table.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_events', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('users', sa.Column('preferences', sqlite.JSON(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
    op.alter_column('payments', 'bill_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('payments', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
    op.alter_column('consumption_audit', 'consumption_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('consumption_audit', 'admin_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('consumption_audit', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('consumption_audit', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
    op.drop_constraint(None, 'consumption', type_='foreignkey')
    op.create_index(op.f('idx_consumption_date'), 'consumption', ['date'], unique=False)
    op.alter_column('consumption', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('consumption', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
    op.drop_column('consumption', 'confirmed_by')
    op.drop_column('consumption', 'request_note')
    op.drop_column('consumption', 'request_status')
    op.drop_column('consumption', 'requested_extra_qty')
    op.drop_column('consumption', 'requested_quantity')
    op.alter_column('bills', 'original_bill_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('bills', 'generated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('bills', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(FALSE)'))
    op.alter_column('bills', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('bills', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index('idx_consumption_archive_user_date', table_name='consumption_archive')
    op.drop_index('idx_consumption_archive_original_id', table_name='consumption_archive')
    op.drop_index('idx_consumption_archive_archived_at', table_name='consumption_archive')
    op.drop_table('consumption_archive')
    op.drop_index('idx_bill_line_items_date', table_name='bill_line_items')
    op.drop_index('idx_bill_line_items_bill_id', table_name='bill_line_items')
    op.drop_table('bill_line_items')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
